import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'SimplCRUD',
  description: 'Generated by next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel='shortcut icon' href='/favicon/favicon.ico'/>
      </head>
      <body className={`${inter.className} bg-gray-900 text-white mx-[250px]`}>
        <Navbar/>
        {children}</body>
    </html>
  )
}
